const std = @import("std");
const glfw = @import("glfw.zig");
const sdl = @import("sdl.zig");

pub const KeyState = enum {
    Up,
    Down,
    Released,
    Pressed,
};

pub const Key = enum {
    SPACE,
    APOSTROPHE,
    COMMA,
    MINUS,
    PERIOD,
    SLASH,
    NUM_0,
    NUM_1,
    NUM_2,
    NUM_3,
    NUM_4,
    NUM_5,
    NUM_6,
    NUM_7,
    NUM_8,
    NUM_9,
    SEMICOLON,
    EQUAL,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    LEFT_BRACKET,
    BACKSLASH,
    RIGHT_BRACKET,
    GRAVE_ACCENT,
    WORLD_1,
    WORLD_2,
    ESCAPE,
    ENTER,
    TAB,
    BACKSPACE,
    INSERT,
    DELETE,
    RIGHT,
    LEFT,
    DOWN,
    UP,
    PAGE_UP,
    PAGE_DOWN,
    HOME,
    END,
    CAPS_LOCK,
    SCROLL_LOCK,
    NUM_LOCK,
    PRINT_SCREEN,
    PAUSE,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    F25,
    KP_0,
    KP_1,
    KP_2,
    KP_3,
    KP_4,
    KP_5,
    KP_6,
    KP_7,
    KP_8,
    KP_9,
    KP_DECIMAL,
    KP_DIVIDE,
    KP_MULTIPLY,
    KP_SUBTRACT,
    KP_ADD,
    KP_ENTER,
    KP_EQUAL,
    LEFT_SHIFT,
    LEFT_CONTROL,
    LEFT_ALT,
    LEFT_SUPER,
    RIGHT_SHIFT,
    RIGHT_CONTROL,
    RIGHT_ALT,
    RIGHT_SUPER,
    MENU,
};

pub fn getGlfwKeyTokenFromKey(key: Key) c_int {
    return switch (key) {
        .SPACE => glfw.c.GLFW_KEY_SPACE,
        .APOSTROPHE => glfw.c.GLFW_KEY_APOSTROPHE,
        .COMMA => glfw.c.GLFW_KEY_COMMA,
        .MINUS => glfw.c.GLFW_KEY_MINUS,
        .PERIOD => glfw.c.GLFW_KEY_PERIOD,
        .SLASH => glfw.c.GLFW_KEY_SLASH,
        .NUM_0 => glfw.c.GLFW_KEY_0,
        .NUM_1 => glfw.c.GLFW_KEY_1,
        .NUM_2 => glfw.c.GLFW_KEY_2,
        .NUM_3 => glfw.c.GLFW_KEY_3,
        .NUM_4 => glfw.c.GLFW_KEY_4,
        .NUM_5 => glfw.c.GLFW_KEY_5,
        .NUM_6 => glfw.c.GLFW_KEY_6,
        .NUM_7 => glfw.c.GLFW_KEY_7,
        .NUM_8 => glfw.c.GLFW_KEY_8,
        .NUM_9 => glfw.c.GLFW_KEY_9,
        .SEMICOLON => glfw.c.GLFW_KEY_SEMICOLON,
        .EQUAL => glfw.c.GLFW_KEY_EQUAL,
        .A => glfw.c.GLFW_KEY_A,
        .B => glfw.c.GLFW_KEY_B,
        .C => glfw.c.GLFW_KEY_C,
        .D => glfw.c.GLFW_KEY_D,
        .E => glfw.c.GLFW_KEY_E,
        .F => glfw.c.GLFW_KEY_F,
        .G => glfw.c.GLFW_KEY_G,
        .H => glfw.c.GLFW_KEY_H,
        .I => glfw.c.GLFW_KEY_I,
        .J => glfw.c.GLFW_KEY_J,
        .K => glfw.c.GLFW_KEY_K,
        .L => glfw.c.GLFW_KEY_L,
        .M => glfw.c.GLFW_KEY_M,
        .N => glfw.c.GLFW_KEY_N,
        .O => glfw.c.GLFW_KEY_O,
        .P => glfw.c.GLFW_KEY_P,
        .Q => glfw.c.GLFW_KEY_Q,
        .R => glfw.c.GLFW_KEY_R,
        .S => glfw.c.GLFW_KEY_S,
        .T => glfw.c.GLFW_KEY_T,
        .U => glfw.c.GLFW_KEY_U,
        .V => glfw.c.GLFW_KEY_V,
        .W => glfw.c.GLFW_KEY_W,
        .X => glfw.c.GLFW_KEY_X,
        .Y => glfw.c.GLFW_KEY_Y,
        .Z => glfw.c.GLFW_KEY_Z,
        .LEFT_BRACKET => glfw.c.GLFW_KEY_LEFT_BRACKET,
        .BACKSLASH => glfw.c.GLFW_KEY_BACKSLASH,
        .RIGHT_BRACKET => glfw.c.GLFW_KEY_RIGHT_BRACKET,
        .GRAVE_ACCENT => glfw.c.GLFW_KEY_GRAVE_ACCENT,
        .WORLD_1 => glfw.c.GLFW_KEY_WORLD_1,
        .WORLD_2 => glfw.c.GLFW_KEY_WORLD_2,
        .ESCAPE => glfw.c.GLFW_KEY_ESCAPE,
        .ENTER => glfw.c.GLFW_KEY_ENTER,
        .TAB => glfw.c.GLFW_KEY_TAB,
        .BACKSPACE => glfw.c.GLFW_KEY_BACKSPACE,
        .INSERT => glfw.c.GLFW_KEY_INSERT,
        .DELETE => glfw.c.GLFW_KEY_DELETE,
        .RIGHT => glfw.c.GLFW_KEY_RIGHT,
        .LEFT => glfw.c.GLFW_KEY_LEFT,
        .DOWN => glfw.c.GLFW_KEY_DOWN,
        .UP => glfw.c.GLFW_KEY_UP,
        .PAGE_UP => glfw.c.GLFW_KEY_PAGE_UP,
        .PAGE_DOWN => glfw.c.GLFW_KEY_PAGE_DOWN,
        .HOME => glfw.c.GLFW_KEY_HOME,
        .END => glfw.c.GLFW_KEY_END,
        .CAPS_LOCK => glfw.c.GLFW_KEY_CAPS_LOCK,
        .SCROLL_LOCK => glfw.c.GLFW_KEY_SCROLL_LOCK,
        .NUM_LOCK => glfw.c.GLFW_KEY_NUM_LOCK,
        .PRINT_SCREEN => glfw.c.GLFW_KEY_PRINT_SCREEN,
        .PAUSE => glfw.c.GLFW_KEY_PAUSE,
        .F1 => glfw.c.GLFW_KEY_F1,
        .F2 => glfw.c.GLFW_KEY_F2,
        .F3 => glfw.c.GLFW_KEY_F3,
        .F4 => glfw.c.GLFW_KEY_F4,
        .F5 => glfw.c.GLFW_KEY_F5,
        .F6 => glfw.c.GLFW_KEY_F6,
        .F7 => glfw.c.GLFW_KEY_F7,
        .F8 => glfw.c.GLFW_KEY_F8,
        .F9 => glfw.c.GLFW_KEY_F9,
        .F10 => glfw.c.GLFW_KEY_F10,
        .F11 => glfw.c.GLFW_KEY_F11,
        .F12 => glfw.c.GLFW_KEY_F12,
        .F13 => glfw.c.GLFW_KEY_F13,
        .F14 => glfw.c.GLFW_KEY_F14,
        .F15 => glfw.c.GLFW_KEY_F15,
        .F16 => glfw.c.GLFW_KEY_F16,
        .F17 => glfw.c.GLFW_KEY_F17,
        .F18 => glfw.c.GLFW_KEY_F18,
        .F19 => glfw.c.GLFW_KEY_F19,
        .F20 => glfw.c.GLFW_KEY_F20,
        .F21 => glfw.c.GLFW_KEY_F21,
        .F22 => glfw.c.GLFW_KEY_F22,
        .F23 => glfw.c.GLFW_KEY_F23,
        .F24 => glfw.c.GLFW_KEY_F24,
        .F25 => glfw.c.GLFW_KEY_F25,
        .KP_0 => glfw.c.GLFW_KEY_KP_0,
        .KP_1 => glfw.c.GLFW_KEY_KP_1,
        .KP_2 => glfw.c.GLFW_KEY_KP_2,
        .KP_3 => glfw.c.GLFW_KEY_KP_3,
        .KP_4 => glfw.c.GLFW_KEY_KP_4,
        .KP_5 => glfw.c.GLFW_KEY_KP_5,
        .KP_6 => glfw.c.GLFW_KEY_KP_6,
        .KP_7 => glfw.c.GLFW_KEY_KP_7,
        .KP_8 => glfw.c.GLFW_KEY_KP_8,
        .KP_9 => glfw.c.GLFW_KEY_KP_9,
        .KP_DECIMAL => glfw.c.GLFW_KEY_KP_DECIMAL,
        .KP_DIVIDE => glfw.c.GLFW_KEY_KP_DIVIDE,
        .KP_MULTIPLY => glfw.c.GLFW_KEY_KP_MULTIPLY,
        .KP_SUBTRACT => glfw.c.GLFW_KEY_KP_SUBTRACT,
        .KP_ADD => glfw.c.GLFW_KEY_KP_ADD,
        .KP_ENTER => glfw.c.GLFW_KEY_KP_ENTER,
        .KP_EQUAL => glfw.c.GLFW_KEY_KP_EQUAL,
        .LEFT_SHIFT => glfw.c.GLFW_KEY_LEFT_SHIFT,
        .LEFT_CONTROL => glfw.c.GLFW_KEY_LEFT_CONTROL,
        .LEFT_ALT => glfw.c.GLFW_KEY_LEFT_ALT,
        .LEFT_SUPER => glfw.c.GLFW_KEY_LEFT_SUPER,
        .RIGHT_SHIFT => glfw.c.GLFW_KEY_RIGHT_SHIFT,
        .RIGHT_CONTROL => glfw.c.GLFW_KEY_RIGHT_CONTROL,
        .RIGHT_ALT => glfw.c.GLFW_KEY_RIGHT_ALT,
        .RIGHT_SUPER => glfw.c.GLFW_KEY_RIGHT_SUPER,
        .MENU => glfw.c.GLFW_KEY_MENU,
    };
}

pub fn getSdlScancodeFromKey(key: Key) usize {
    return switch (key) {
        .SPACE => sdl.c.SDL_SCANCODE_SPACE,
        .APOSTROPHE => sdl.c.SDL_SCANCODE_APOSTROPHE,
        .COMMA => sdl.c.SDL_SCANCODE_COMMA,
        .MINUS => sdl.c.SDL_SCANCODE_MINUS,
        .PERIOD => sdl.c.SDL_SCANCODE_PERIOD,
        .SLASH => sdl.c.SDL_SCANCODE_SLASH,
        .NUM_0 => sdl.c.SDL_SCANCODE_0,
        .NUM_1 => sdl.c.SDL_SCANCODE_1,
        .NUM_2 => sdl.c.SDL_SCANCODE_2,
        .NUM_3 => sdl.c.SDL_SCANCODE_3,
        .NUM_4 => sdl.c.SDL_SCANCODE_4,
        .NUM_5 => sdl.c.SDL_SCANCODE_5,
        .NUM_6 => sdl.c.SDL_SCANCODE_6,
        .NUM_7 => sdl.c.SDL_SCANCODE_7,
        .NUM_8 => sdl.c.SDL_SCANCODE_8,
        .NUM_9 => sdl.c.SDL_SCANCODE_9,
        .SEMICOLON => sdl.c.SDL_SCANCODE_SEMICOLON,
        .EQUAL => sdl.c.SDL_SCANCODE_EQUALS,
        .A => sdl.c.SDL_SCANCODE_A,
        .B => sdl.c.SDL_SCANCODE_B,
        .C => sdl.c.SDL_SCANCODE_C,
        .D => sdl.c.SDL_SCANCODE_D,
        .E => sdl.c.SDL_SCANCODE_E,
        .F => sdl.c.SDL_SCANCODE_F,
        .G => sdl.c.SDL_SCANCODE_G,
        .H => sdl.c.SDL_SCANCODE_H,
        .I => sdl.c.SDL_SCANCODE_I,
        .J => sdl.c.SDL_SCANCODE_J,
        .K => sdl.c.SDL_SCANCODE_K,
        .L => sdl.c.SDL_SCANCODE_L,
        .M => sdl.c.SDL_SCANCODE_M,
        .N => sdl.c.SDL_SCANCODE_N,
        .O => sdl.c.SDL_SCANCODE_O,
        .P => sdl.c.SDL_SCANCODE_P,
        .Q => sdl.c.SDL_SCANCODE_Q,
        .R => sdl.c.SDL_SCANCODE_R,
        .S => sdl.c.SDL_SCANCODE_S,
        .T => sdl.c.SDL_SCANCODE_T,
        .U => sdl.c.SDL_SCANCODE_U,
        .V => sdl.c.SDL_SCANCODE_V,
        .W => sdl.c.SDL_SCANCODE_W,
        .X => sdl.c.SDL_SCANCODE_X,
        .Y => sdl.c.SDL_SCANCODE_Y,
        .Z => sdl.c.SDL_SCANCODE_Z,
        .LEFT_BRACKET => sdl.c.SDL_SCANCODE_LEFTBRACKET,
        .BACKSLASH => sdl.c.SDL_SCANCODE_BACKSLASH,
        .RIGHT_BRACKET => sdl.c.SDL_SCANCODE_RIGHTBRACKET,
        .GRAVE_ACCENT => sdl.c.SDL_SCANCODE_GRAVE,
        .WORLD_1 => sdl.c.SDL_SCANCODE_NONUSBACKSLASH, // no exact GLFW equivalent
        .WORLD_2 => sdl.c.SDL_SCANCODE_NONUSHASH, // no exact GLFW equivalent
        .ESCAPE => sdl.c.SDL_SCANCODE_ESCAPE,
        .ENTER => sdl.c.SDL_SCANCODE_RETURN,
        .TAB => sdl.c.SDL_SCANCODE_TAB,
        .BACKSPACE => sdl.c.SDL_SCANCODE_BACKSPACE,
        .INSERT => sdl.c.SDL_SCANCODE_INSERT,
        .DELETE => sdl.c.SDL_SCANCODE_DELETE,
        .RIGHT => sdl.c.SDL_SCANCODE_RIGHT,
        .LEFT => sdl.c.SDL_SCANCODE_LEFT,
        .DOWN => sdl.c.SDL_SCANCODE_DOWN,
        .UP => sdl.c.SDL_SCANCODE_UP,
        .PAGE_UP => sdl.c.SDL_SCANCODE_PAGEUP,
        .PAGE_DOWN => sdl.c.SDL_SCANCODE_PAGEDOWN,
        .HOME => sdl.c.SDL_SCANCODE_HOME,
        .END => sdl.c.SDL_SCANCODE_END,
        .CAPS_LOCK => sdl.c.SDL_SCANCODE_CAPSLOCK,
        .SCROLL_LOCK => sdl.c.SDL_SCANCODE_SCROLLLOCK,
        .NUM_LOCK => sdl.c.SDL_SCANCODE_NUMLOCKCLEAR,
        .PRINT_SCREEN => sdl.c.SDL_SCANCODE_PRINTSCREEN,
        .PAUSE => sdl.c.SDL_SCANCODE_PAUSE,
        .F1 => sdl.c.SDL_SCANCODE_F1,
        .F2 => sdl.c.SDL_SCANCODE_F2,
        .F3 => sdl.c.SDL_SCANCODE_F3,
        .F4 => sdl.c.SDL_SCANCODE_F4,
        .F5 => sdl.c.SDL_SCANCODE_F5,
        .F6 => sdl.c.SDL_SCANCODE_F6,
        .F7 => sdl.c.SDL_SCANCODE_F7,
        .F8 => sdl.c.SDL_SCANCODE_F8,
        .F9 => sdl.c.SDL_SCANCODE_F9,
        .F10 => sdl.c.SDL_SCANCODE_F10,
        .F11 => sdl.c.SDL_SCANCODE_F11,
        .F12 => sdl.c.SDL_SCANCODE_F12,
        .F13 => sdl.c.SDL_SCANCODE_F13,
        .F14 => sdl.c.SDL_SCANCODE_F14,
        .F15 => sdl.c.SDL_SCANCODE_F15,
        .F16 => sdl.c.SDL_SCANCODE_F16,
        .F17 => sdl.c.SDL_SCANCODE_F17,
        .F18 => sdl.c.SDL_SCANCODE_F18,
        .F19 => sdl.c.SDL_SCANCODE_F19,
        .F20 => sdl.c.SDL_SCANCODE_F20,
        .F21 => sdl.c.SDL_SCANCODE_F21,
        .F22 => sdl.c.SDL_SCANCODE_F22,
        .F23 => sdl.c.SDL_SCANCODE_F23,
        .F24 => sdl.c.SDL_SCANCODE_F24,
        .F25 => sdl.c.SDL_SCANCODE_UNKNOWN, // SDL only defines up to F24
        .KP_0 => sdl.c.SDL_SCANCODE_KP_0,
        .KP_1 => sdl.c.SDL_SCANCODE_KP_1,
        .KP_2 => sdl.c.SDL_SCANCODE_KP_2,
        .KP_3 => sdl.c.SDL_SCANCODE_KP_3,
        .KP_4 => sdl.c.SDL_SCANCODE_KP_4,
        .KP_5 => sdl.c.SDL_SCANCODE_KP_5,
        .KP_6 => sdl.c.SDL_SCANCODE_KP_6,
        .KP_7 => sdl.c.SDL_SCANCODE_KP_7,
        .KP_8 => sdl.c.SDL_SCANCODE_KP_8,
        .KP_9 => sdl.c.SDL_SCANCODE_KP_9,
        .KP_DECIMAL => sdl.c.SDL_SCANCODE_KP_PERIOD,
        .KP_DIVIDE => sdl.c.SDL_SCANCODE_KP_DIVIDE,
        .KP_MULTIPLY => sdl.c.SDL_SCANCODE_KP_MULTIPLY,
        .KP_SUBTRACT => sdl.c.SDL_SCANCODE_KP_MINUS,
        .KP_ADD => sdl.c.SDL_SCANCODE_KP_PLUS,
        .KP_ENTER => sdl.c.SDL_SCANCODE_KP_ENTER,
        .KP_EQUAL => sdl.c.SDL_SCANCODE_KP_EQUALS,
        .LEFT_SHIFT => sdl.c.SDL_SCANCODE_LSHIFT,
        .LEFT_CONTROL => sdl.c.SDL_SCANCODE_LCTRL,
        .LEFT_ALT => sdl.c.SDL_SCANCODE_LALT,
        .LEFT_SUPER => sdl.c.SDL_SCANCODE_LGUI,
        .RIGHT_SHIFT => sdl.c.SDL_SCANCODE_RSHIFT,
        .RIGHT_CONTROL => sdl.c.SDL_SCANCODE_RCTRL,
        .RIGHT_ALT => sdl.c.SDL_SCANCODE_RALT,
        .RIGHT_SUPER => sdl.c.SDL_SCANCODE_RGUI,
        .MENU => sdl.c.SDL_SCANCODE_MENU,
    };
}

pub fn getKeyFromSdlScancode(scancode: usize) Key {
    return switch (scancode) {
        sdl.c.SDL_SCANCODE_SPACE => .SPACE,
        sdl.c.SDL_SCANCODE_APOSTROPHE => .APOSTROPHE,
        sdl.c.SDL_SCANCODE_COMMA => .COMMA,
        sdl.c.SDL_SCANCODE_MINUS => .MINUS,
        sdl.c.SDL_SCANCODE_PERIOD => .PERIOD,
        sdl.c.SDL_SCANCODE_SLASH => .SLASH,
        sdl.c.SDL_SCANCODE_0 => .NUM_0,
        sdl.c.SDL_SCANCODE_1 => .NUM_1,
        sdl.c.SDL_SCANCODE_2 => .NUM_2,
        sdl.c.SDL_SCANCODE_3 => .NUM_3,
        sdl.c.SDL_SCANCODE_4 => .NUM_4,
        sdl.c.SDL_SCANCODE_5 => .NUM_5,
        sdl.c.SDL_SCANCODE_6 => .NUM_6,
        sdl.c.SDL_SCANCODE_7 => .NUM_7,
        sdl.c.SDL_SCANCODE_8 => .NUM_8,
        sdl.c.SDL_SCANCODE_9 => .NUM_9,
        sdl.c.SDL_SCANCODE_SEMICOLON => .SEMICOLON,
        sdl.c.SDL_SCANCODE_EQUALS => .EQUAL,
        sdl.c.SDL_SCANCODE_A => .A,
        sdl.c.SDL_SCANCODE_B => .B,
        sdl.c.SDL_SCANCODE_C => .C,
        sdl.c.SDL_SCANCODE_D => .D,
        sdl.c.SDL_SCANCODE_E => .E,
        sdl.c.SDL_SCANCODE_F => .F,
        sdl.c.SDL_SCANCODE_G => .G,
        sdl.c.SDL_SCANCODE_H => .H,
        sdl.c.SDL_SCANCODE_I => .I,
        sdl.c.SDL_SCANCODE_J => .J,
        sdl.c.SDL_SCANCODE_K => .K,
        sdl.c.SDL_SCANCODE_L => .L,
        sdl.c.SDL_SCANCODE_M => .M,
        sdl.c.SDL_SCANCODE_N => .N,
        sdl.c.SDL_SCANCODE_O => .O,
        sdl.c.SDL_SCANCODE_P => .P,
        sdl.c.SDL_SCANCODE_Q => .Q,
        sdl.c.SDL_SCANCODE_R => .R,
        sdl.c.SDL_SCANCODE_S => .S,
        sdl.c.SDL_SCANCODE_T => .T,
        sdl.c.SDL_SCANCODE_U => .U,
        sdl.c.SDL_SCANCODE_V => .V,
        sdl.c.SDL_SCANCODE_W => .W,
        sdl.c.SDL_SCANCODE_X => .X,
        sdl.c.SDL_SCANCODE_Y => .Y,
        sdl.c.SDL_SCANCODE_Z => .Z,
        sdl.c.SDL_SCANCODE_LEFTBRACKET => .LEFT_BRACKET,
        sdl.c.SDL_SCANCODE_BACKSLASH => .BACKSLASH,
        sdl.c.SDL_SCANCODE_RIGHTBRACKET => .RIGHT_BRACKET,
        sdl.c.SDL_SCANCODE_GRAVE => .GRAVE_ACCENT,
        sdl.c.SDL_SCANCODE_NONUSBACKSLASH => .WORLD_1, // no exact GLFW equivalent
        sdl.c.SDL_SCANCODE_NONUSHASH => .WORLD_2, // no exact GLFW equivalent
        sdl.c.SDL_SCANCODE_ESCAPE => .ESCAPE,
        sdl.c.SDL_SCANCODE_RETURN => .ENTER,
        sdl.c.SDL_SCANCODE_TAB => .TAB,
        sdl.c.SDL_SCANCODE_BACKSPACE => .BACKSPACE,
        sdl.c.SDL_SCANCODE_INSERT => .INSERT,
        sdl.c.SDL_SCANCODE_DELETE => .DELETE,
        sdl.c.SDL_SCANCODE_RIGHT => .RIGHT,
        sdl.c.SDL_SCANCODE_LEFT => .LEFT,
        sdl.c.SDL_SCANCODE_DOWN => .DOWN,
        sdl.c.SDL_SCANCODE_UP => .UP,
        sdl.c.SDL_SCANCODE_PAGEUP => .PAGE_UP,
        sdl.c.SDL_SCANCODE_PAGEDOWN => .PAGE_DOWN,
        sdl.c.SDL_SCANCODE_HOME => .HOME,
        sdl.c.SDL_SCANCODE_END => .END,
        sdl.c.SDL_SCANCODE_CAPSLOCK => .CAPS_LOCK,
        sdl.c.SDL_SCANCODE_SCROLLLOCK => .SCROLL_LOCK,
        sdl.c.SDL_SCANCODE_NUMLOCKCLEAR => .NUM_LOCK,
        sdl.c.SDL_SCANCODE_PRINTSCREEN => .PRINT_SCREEN,
        sdl.c.SDL_SCANCODE_PAUSE => .PAUSE,
        sdl.c.SDL_SCANCODE_F1 => .F1,
        sdl.c.SDL_SCANCODE_F2 => .F2,
        sdl.c.SDL_SCANCODE_F3 => .F3,
        sdl.c.SDL_SCANCODE_F4 => .F4,
        sdl.c.SDL_SCANCODE_F5 => .F5,
        sdl.c.SDL_SCANCODE_F6 => .F6,
        sdl.c.SDL_SCANCODE_F7 => .F7,
        sdl.c.SDL_SCANCODE_F8 => .F8,
        sdl.c.SDL_SCANCODE_F9 => .F9,
        sdl.c.SDL_SCANCODE_F10 => .F10,
        sdl.c.SDL_SCANCODE_F11 => .F11,
        sdl.c.SDL_SCANCODE_F12 => .F12,
        sdl.c.SDL_SCANCODE_F13 => .F13,
        sdl.c.SDL_SCANCODE_F14 => .F14,
        sdl.c.SDL_SCANCODE_F15 => .F15,
        sdl.c.SDL_SCANCODE_F16 => .F16,
        sdl.c.SDL_SCANCODE_F17 => .F17,
        sdl.c.SDL_SCANCODE_F18 => .F18,
        sdl.c.SDL_SCANCODE_F19 => .F19,
        sdl.c.SDL_SCANCODE_F20 => .F20,
        sdl.c.SDL_SCANCODE_F21 => .F21,
        sdl.c.SDL_SCANCODE_F22 => .F22,
        sdl.c.SDL_SCANCODE_F23 => .F23,
        sdl.c.SDL_SCANCODE_F24 => .F24,
        sdl.c.SDL_SCANCODE_UNKNOWN => .F25, // SDL only defines up to F24
        sdl.c.SDL_SCANCODE_KP_0 => .KP_0,
        sdl.c.SDL_SCANCODE_KP_1 => .KP_1,
        sdl.c.SDL_SCANCODE_KP_2 => .KP_2,
        sdl.c.SDL_SCANCODE_KP_3 => .KP_3,
        sdl.c.SDL_SCANCODE_KP_4 => .KP_4,
        sdl.c.SDL_SCANCODE_KP_5 => .KP_5,
        sdl.c.SDL_SCANCODE_KP_6 => .KP_6,
        sdl.c.SDL_SCANCODE_KP_7 => .KP_7,
        sdl.c.SDL_SCANCODE_KP_8 => .KP_8,
        sdl.c.SDL_SCANCODE_KP_9 => .KP_9,
        sdl.c.SDL_SCANCODE_KP_PERIOD => .KP_DECIMAL,
        sdl.c.SDL_SCANCODE_KP_DIVIDE => .KP_DIVIDE,
        sdl.c.SDL_SCANCODE_KP_MULTIPLY => .KP_MULTIPLY,
        sdl.c.SDL_SCANCODE_KP_MINUS => .KP_SUBTRACT,
        sdl.c.SDL_SCANCODE_KP_PLUS => .KP_ADD,
        sdl.c.SDL_SCANCODE_KP_ENTER => .KP_ENTER,
        sdl.c.SDL_SCANCODE_KP_EQUALS => .KP_EQUAL,
        sdl.c.SDL_SCANCODE_LSHIFT => .LEFT_SHIFT,
        sdl.c.SDL_SCANCODE_LCTRL => .LEFT_CONTROL,
        sdl.c.SDL_SCANCODE_LALT => .LEFT_ALT,
        sdl.c.SDL_SCANCODE_LGUI => .LEFT_SUPER,
        sdl.c.SDL_SCANCODE_RSHIFT => .RIGHT_SHIFT,
        sdl.c.SDL_SCANCODE_RCTRL => .RIGHT_CONTROL,
        sdl.c.SDL_SCANCODE_RALT => .RIGHT_ALT,
        sdl.c.SDL_SCANCODE_RGUI => .RIGHT_SUPER,
        sdl.c.SDL_SCANCODE_MENU => .MENU,
        else => .Q,
    };
}
