const std = @import("std");
const glfw = @import("glfw.zig");
const c = glfw.c;

pub const KeyState = enum {
    Up,
    Down,
    Released,
    Pressed,
};

pub const Key = enum {
    SPACE,
    APOSTROPHE,
    COMMA,
    MINUS,
    PERIOD,
    SLASH,
    NUM_0,
    NUM_1,
    NUM_2,
    NUM_3,
    NUM_4,
    NUM_5,
    NUM_6,
    NUM_7,
    NUM_8,
    NUM_9,
    SEMICOLON,
    EQUAL,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    LEFT_BRACKET,
    BACKSLASH,
    RIGHT_BRACKET,
    GRAVE_ACCENT,
    WORLD_1,
    WORLD_2,
    ESCAPE,
    ENTER,
    TAB,
    BACKSPACE,
    INSERT,
    DELETE,
    RIGHT,
    LEFT,
    DOWN,
    UP,
    PAGE_UP,
    PAGE_DOWN,
    HOME,
    END,
    CAPS_LOCK,
    SCROLL_LOCK,
    NUM_LOCK,
    PRINT_SCREEN,
    PAUSE,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    F25,
    KP_0,
    KP_1,
    KP_2,
    KP_3,
    KP_4,
    KP_5,
    KP_6,
    KP_7,
    KP_8,
    KP_9,
    KP_DECIMAL,
    KP_DIVIDE,
    KP_MULTIPLY,
    KP_SUBTRACT,
    KP_ADD,
    KP_ENTER,
    KP_EQUAL,
    LEFT_SHIFT,
    LEFT_CONTROL,
    LEFT_ALT,
    LEFT_SUPER,
    RIGHT_SHIFT,
    RIGHT_CONTROL,
    RIGHT_ALT,
    RIGHT_SUPER,
    MENU,
};

pub fn getGlfwKeyTokenFromKey(key: Key) c_int {
    return switch (key) {
        .SPACE => c.GLFW_KEY_SPACE,
        .APOSTROPHE => c.GLFW_KEY_APOSTROPHE,
        .COMMA => c.GLFW_KEY_COMMA,
        .MINUS => c.GLFW_KEY_MINUS,
        .PERIOD => c.GLFW_KEY_PERIOD,
        .SLASH => c.GLFW_KEY_SLASH,
        .NUM_0 => c.GLFW_KEY_0,
        .NUM_1 => c.GLFW_KEY_1,
        .NUM_2 => c.GLFW_KEY_2,
        .NUM_3 => c.GLFW_KEY_3,
        .NUM_4 => c.GLFW_KEY_4,
        .NUM_5 => c.GLFW_KEY_5,
        .NUM_6 => c.GLFW_KEY_6,
        .NUM_7 => c.GLFW_KEY_7,
        .NUM_8 => c.GLFW_KEY_8,
        .NUM_9 => c.GLFW_KEY_9,
        .SEMICOLON => c.GLFW_KEY_SEMICOLON,
        .EQUAL => c.GLFW_KEY_EQUAL,
        .A => c.GLFW_KEY_A,
        .B => c.GLFW_KEY_B,
        .C => c.GLFW_KEY_C,
        .D => c.GLFW_KEY_D,
        .E => c.GLFW_KEY_E,
        .F => c.GLFW_KEY_F,
        .G => c.GLFW_KEY_G,
        .H => c.GLFW_KEY_H,
        .I => c.GLFW_KEY_I,
        .J => c.GLFW_KEY_J,
        .K => c.GLFW_KEY_K,
        .L => c.GLFW_KEY_L,
        .M => c.GLFW_KEY_M,
        .N => c.GLFW_KEY_N,
        .O => c.GLFW_KEY_O,
        .P => c.GLFW_KEY_P,
        .Q => c.GLFW_KEY_Q,
        .R => c.GLFW_KEY_R,
        .S => c.GLFW_KEY_S,
        .T => c.GLFW_KEY_T,
        .U => c.GLFW_KEY_U,
        .V => c.GLFW_KEY_V,
        .W => c.GLFW_KEY_W,
        .X => c.GLFW_KEY_X,
        .Y => c.GLFW_KEY_Y,
        .Z => c.GLFW_KEY_Z,
        .LEFT_BRACKET => c.GLFW_KEY_LEFT_BRACKET,
        .BACKSLASH => c.GLFW_KEY_BACKSLASH,
        .RIGHT_BRACKET => c.GLFW_KEY_RIGHT_BRACKET,
        .GRAVE_ACCENT => c.GLFW_KEY_GRAVE_ACCENT,
        .WORLD_1 => c.GLFW_KEY_WORLD_1,
        .WORLD_2 => c.GLFW_KEY_WORLD_2,
        .ESCAPE => c.GLFW_KEY_ESCAPE,
        .ENTER => c.GLFW_KEY_ENTER,
        .TAB => c.GLFW_KEY_TAB,
        .BACKSPACE => c.GLFW_KEY_BACKSPACE,
        .INSERT => c.GLFW_KEY_INSERT,
        .DELETE => c.GLFW_KEY_DELETE,
        .RIGHT => c.GLFW_KEY_RIGHT,
        .LEFT => c.GLFW_KEY_LEFT,
        .DOWN => c.GLFW_KEY_DOWN,
        .UP => c.GLFW_KEY_UP,
        .PAGE_UP => c.GLFW_KEY_PAGE_UP,
        .PAGE_DOWN => c.GLFW_KEY_PAGE_DOWN,
        .HOME => c.GLFW_KEY_HOME,
        .END => c.GLFW_KEY_END,
        .CAPS_LOCK => c.GLFW_KEY_CAPS_LOCK,
        .SCROLL_LOCK => c.GLFW_KEY_SCROLL_LOCK,
        .NUM_LOCK => c.GLFW_KEY_NUM_LOCK,
        .PRINT_SCREEN => c.GLFW_KEY_PRINT_SCREEN,
        .PAUSE => c.GLFW_KEY_PAUSE,
        .F1 => c.GLFW_KEY_F1,
        .F2 => c.GLFW_KEY_F2,
        .F3 => c.GLFW_KEY_F3,
        .F4 => c.GLFW_KEY_F4,
        .F5 => c.GLFW_KEY_F5,
        .F6 => c.GLFW_KEY_F6,
        .F7 => c.GLFW_KEY_F7,
        .F8 => c.GLFW_KEY_F8,
        .F9 => c.GLFW_KEY_F9,
        .F10 => c.GLFW_KEY_F10,
        .F11 => c.GLFW_KEY_F11,
        .F12 => c.GLFW_KEY_F12,
        .F13 => c.GLFW_KEY_F13,
        .F14 => c.GLFW_KEY_F14,
        .F15 => c.GLFW_KEY_F15,
        .F16 => c.GLFW_KEY_F16,
        .F17 => c.GLFW_KEY_F17,
        .F18 => c.GLFW_KEY_F18,
        .F19 => c.GLFW_KEY_F19,
        .F20 => c.GLFW_KEY_F20,
        .F21 => c.GLFW_KEY_F21,
        .F22 => c.GLFW_KEY_F22,
        .F23 => c.GLFW_KEY_F23,
        .F24 => c.GLFW_KEY_F24,
        .F25 => c.GLFW_KEY_F25,
        .KP_0 => c.GLFW_KEY_KP_0,
        .KP_1 => c.GLFW_KEY_KP_1,
        .KP_2 => c.GLFW_KEY_KP_2,
        .KP_3 => c.GLFW_KEY_KP_3,
        .KP_4 => c.GLFW_KEY_KP_4,
        .KP_5 => c.GLFW_KEY_KP_5,
        .KP_6 => c.GLFW_KEY_KP_6,
        .KP_7 => c.GLFW_KEY_KP_7,
        .KP_8 => c.GLFW_KEY_KP_8,
        .KP_9 => c.GLFW_KEY_KP_9,
        .KP_DECIMAL => c.GLFW_KEY_KP_DECIMAL,
        .KP_DIVIDE => c.GLFW_KEY_KP_DIVIDE,
        .KP_MULTIPLY => c.GLFW_KEY_KP_MULTIPLY,
        .KP_SUBTRACT => c.GLFW_KEY_KP_SUBTRACT,
        .KP_ADD => c.GLFW_KEY_KP_ADD,
        .KP_ENTER => c.GLFW_KEY_KP_ENTER,
        .KP_EQUAL => c.GLFW_KEY_KP_EQUAL,
        .LEFT_SHIFT => c.GLFW_KEY_LEFT_SHIFT,
        .LEFT_CONTROL => c.GLFW_KEY_LEFT_CONTROL,
        .LEFT_ALT => c.GLFW_KEY_LEFT_ALT,
        .LEFT_SUPER => c.GLFW_KEY_LEFT_SUPER,
        .RIGHT_SHIFT => c.GLFW_KEY_RIGHT_SHIFT,
        .RIGHT_CONTROL => c.GLFW_KEY_RIGHT_CONTROL,
        .RIGHT_ALT => c.GLFW_KEY_RIGHT_ALT,
        .RIGHT_SUPER => c.GLFW_KEY_RIGHT_SUPER,
        .MENU => c.GLFW_KEY_MENU,
    };
}
